# Generated by Django 3.2.5 on 2026-02-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20260214_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='published_at',
        ),
    ]
